Repository AY1920S1-CS2103T-T13-3/main, pull requests merged in 2019-10, with the labels that each got.

#39 Finished preliminary UI design
  src/main/java/seedu/address/ui/Cashier.java
  src/main/java/seedu/address/ui/Home.java
  src/main/java/seedu/address/ui/Inventory.java
  src/main/java/seedu/address/ui/Lion.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/Overview.java
  src/main/java/seedu/address/ui/Reimbursements.java
  src/main/resources/view/Cashier.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Home.fxml
  src/main/resources/view/Inventory.fxml
  src/main/resources/view/Lion.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/Overview.fxml
  src/main/resources/view/Reimbursements.fxml
Labels: enhancement

#52 add reimbursement classes for reimbursement tab
  src/main/java/seedu/address/reimbursement/Reimbursement.java
  src/main/java/seedu/address/reimbursement/ReimbursementList.java
  src/main/java/seedu/address/reimbursement/ReimbursementRecord.java
  src/main/java/seedu/address/reimbursement/exceptions/ReimbursementNotFoundException.java
  src/main/java/seedu/address/reimbursement/exceptions/ReimbursementUpdatedException.java
Labels: enhancement

#55 help
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/person/logic/commands/CommandResult.java
  src/main/java/seedu/address/reimbursement/storage/Storage.java
  src/main/java/seedu/address/transaction/Main.java
  src/main/java/seedu/address/transaction/commands/AddCommand.java
  src/main/java/seedu/address/transaction/commands/Command.java
  src/main/java/seedu/address/transaction/commands/CommandResult.java
  src/main/java/seedu/address/transaction/commands/DeleteCommand.java
  src/main/java/seedu/address/transaction/commands/EditCommand.java
  src/main/java/seedu/address/transaction/logic/AddCommandParser.java
  src/main/java/seedu/address/transaction/logic/LogicManager.java
  src/main/java/seedu/address/transaction/model/Model.java
  src/main/java/seedu/address/transaction/model/ModelManager.java
  src/main/java/seedu/address/transaction/model/exception/NoSuchPersonException.java
  src/main/java/seedu/address/transaction/ui/TransactionMessages.java
  src/main/java/seedu/address/util/OverallCommandResult.java
Labels: Integration

#100 Fixed UI for all tabs except Overview.
  src/main/resources/view/Cashier.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Home.fxml
  src/main/resources/view/Inventory.fxml
  src/main/resources/view/Lion.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/Overview.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/Reimbursements.fxml
Labels: Integration, type.Enhancement

#108 Adds exit command to transaction tab and adds delete by person command.
  src/main/java/seedu/address/cashier/model/ModelManager.java
  src/main/java/seedu/address/inventory/commands/DeleteCommand.java
  src/main/java/seedu/address/inventory/logic/InventoryTabParser.java
  src/main/java/seedu/address/person/logic/commands/Command.java
  src/main/java/seedu/address/person/logic/commands/CommandResult.java
  src/main/java/seedu/address/person/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/person/model/AddressBook.java
  src/main/java/seedu/address/person/model/person/Person.java
  src/main/java/seedu/address/reimbursement/logic/ReimbursementTabParser.java
  src/main/java/seedu/address/transaction/commands/CommandResult.java
  src/main/java/seedu/address/transaction/commands/DeleteCommand.java
  src/main/java/seedu/address/transaction/commands/DeleteIndexCommand.java
  src/main/java/seedu/address/transaction/commands/DeleteNameCommand.java
  src/main/java/seedu/address/transaction/commands/ExitCommand.java
  src/main/java/seedu/address/transaction/logic/DeleteCommandParser.java
  src/main/java/seedu/address/transaction/logic/Logic.java
  src/main/java/seedu/address/transaction/logic/LogicManager.java
  src/main/java/seedu/address/transaction/logic/TransactionTabParser.java
  src/main/java/seedu/address/transaction/model/Model.java
  src/main/java/seedu/address/transaction/model/ModelManager.java
  src/main/java/seedu/address/transaction/model/Transaction.java
  src/main/java/seedu/address/transaction/ui/TransactionMessages.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/util/OverallCommand.java
  src/main/java/seedu/address/util/OverallCommandResult.java
  src/test/java/seedu/address/person/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/person/logic/parser/DeleteCommandParserTest.java
Labels: Transaction, enhancement, priority.Medium, type.Task

#123 Reimbursement - Bug fixing week 9
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/reimbursement/commands/ListCommand.java
  src/main/java/seedu/address/reimbursement/commands/SortAmountCommand.java
  src/main/java/seedu/address/reimbursement/commands/SortDeadlineCommand.java
  src/main/java/seedu/address/reimbursement/commands/SortNameCommand.java
  src/main/java/seedu/address/reimbursement/logic/Logic.java
  src/main/java/seedu/address/reimbursement/logic/LogicManager.java
  src/main/java/seedu/address/reimbursement/logic/ReimbursementTabParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/reimbursement/model/Model.java
  src/main/java/seedu/address/reimbursement/model/ModelManager.java
  src/main/java/seedu/address/reimbursement/model/Reimbursement.java
  src/main/java/seedu/address/reimbursement/model/ReimbursementList.java
  src/main/java/seedu/address/reimbursement/model/comparators/SortByAmount.java
  src/main/java/seedu/address/reimbursement/model/util/Deadline.java
  src/main/java/seedu/address/reimbursement/model/util/Description.java
  src/main/java/seedu/address/reimbursement/storage/Storage.java
  src/main/java/seedu/address/reimbursement/storage/StorageManager.java
  src/main/java/seedu/address/reimbursement/ui/ReimbursementMessages.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/Reimbursements.java
  src/main/resources/view/Reimbursements.fxml
Labels: Reimbursement, type.Bug

#126 Fixed bug for updating transaction storage from reimbursements and added javadocs
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/overview/logic/LogicManager.java
  src/main/java/seedu/address/reimbursement/logic/LogicManager.java
  src/main/java/seedu/address/reimbursement/model/Reimbursement.java
  src/main/java/seedu/address/reimbursement/storage/StorageManager.java
  src/main/java/seedu/address/transaction/commands/BackCommand.java
  src/main/java/seedu/address/transaction/commands/Command.java
  src/main/java/seedu/address/transaction/commands/DeleteCommand.java
  src/main/java/seedu/address/transaction/commands/DeleteIndexCommand.java
  src/main/java/seedu/address/transaction/logic/AddCommandParser.java
  src/main/java/seedu/address/transaction/logic/DeleteCommandParser.java
  src/main/java/seedu/address/transaction/logic/FindCommandParser.java
  src/main/java/seedu/address/transaction/logic/LogicManager.java
  src/main/java/seedu/address/transaction/logic/TransactionTabParser.java
  src/main/java/seedu/address/transaction/model/ModelManager.java
  src/main/java/seedu/address/transaction/model/Transaction.java
  src/main/java/seedu/address/transaction/ui/TransactionMessages.java
  src/main/java/seedu/address/transaction/util/TransactionList.java
Labels: Integration

#133 Integrates all packages to use common multimap, tokenizer, clisyntax and change transactions to use observable list
  src/main/java/seedu/address/cashier/commands/AddCommand.java
  src/main/java/seedu/address/cashier/logic/AddCommandParser.java
  src/main/java/seedu/address/cashier/logic/ArgumentMultimap.java
  src/main/java/seedu/address/cashier/logic/ArgumentTokenizer.java
  src/main/java/seedu/address/cashier/logic/CliSyntax.java
  src/main/java/seedu/address/cashier/logic/EditCommandParser.java
  src/main/java/seedu/address/cashier/logic/Prefix.java
  src/main/java/seedu/address/inventory/logic/AddCommandParser.java
  src/main/java/seedu/address/inventory/logic/ArgumentMultimap.java
  src/main/java/seedu/address/inventory/logic/CliSyntax.java
  src/main/java/seedu/address/inventory/logic/EditCommandParser.java
  src/main/java/seedu/address/person/logic/commands/AddCommand.java
  src/main/java/seedu/address/person/logic/commands/EditCommand.java
  src/main/java/seedu/address/person/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/person/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/person/logic/parser/CliSyntax.java
  src/main/java/seedu/address/person/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/person/logic/parser/Prefix.java
  src/main/java/seedu/address/reimbursement/commands/SortAmountCommand.java
  src/main/java/seedu/address/reimbursement/commands/SortCommand.java
  src/main/java/seedu/address/reimbursement/commands/SortDeadlineCommand.java
  src/main/java/seedu/address/reimbursement/commands/SortNameCommand.java
  src/main/java/seedu/address/reimbursement/logic/ReimbursementTabParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/reimbursement/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/reimbursement/logic/parser/CliSyntax.java
  src/main/java/seedu/address/reimbursement/logic/parser/DeadlineCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/DoneCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/ExitCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/Prefix.java
  src/main/java/seedu/address/reimbursement/logic/parser/SortAmountCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/SortDeadlineCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/SortNameCommandParser.java
  src/main/java/seedu/address/reimbursement/ui/ReimbursementMessages.java
  src/main/java/seedu/address/transaction/commands/CommandResult.java
  src/main/java/seedu/address/transaction/commands/EditCommand.java
  src/main/java/seedu/address/transaction/logic/AddCommandParser.java
  src/main/java/seedu/address/transaction/logic/ArgumentMultimap.java
  src/main/java/seedu/address/transaction/logic/ArgumentTokenizer.java
  src/main/java/seedu/address/transaction/logic/CliSyntax.java
  src/main/java/seedu/address/transaction/logic/DeleteCommandParser.java
  src/main/java/seedu/address/transaction/logic/EditCommandParser.java
  src/main/java/seedu/address/transaction/logic/Prefix.java
  src/main/java/seedu/address/transaction/logic/TransactionTabParser.java
  src/main/java/seedu/address/transaction/util/TransactionList.java
  src/main/java/seedu/address/util/ArgumentMultimap.java
  src/main/java/seedu/address/util/ArgumentTokenizer.java
  src/main/java/seedu/address/util/CliSyntax.java
  src/main/java/seedu/address/util/Prefix.java
  src/main/resources/view/Home.fxml
  src/main/resources/view/Inventory.fxml
  src/test/java/seedu/address/person/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/transaction/commands/AddCommandTest.java
Labels: Integration

#134 Adds tab navigation command
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/util/OverallCommand.java
  src/main/resources/view/MainWindow.fxml
Labels: enhancement

#147 update back command and fix find command bug
  src/main/java/seedu/address/reimbursement/commands/BackCommand.java
  src/main/java/seedu/address/reimbursement/logic/ReimbursementTabParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/BackCommandParser.java
  src/main/java/seedu/address/reimbursement/model/Reimbursement.java
  src/main/java/seedu/address/reimbursement/ui/ReimbursementMessages.java
Labels: Integration, Reimbursement

#150 Update reimbursements when edit person
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/person/logic/commands/EditCommand.java
  src/main/java/seedu/address/reimbursement/logic/Logic.java
  src/main/java/seedu/address/reimbursement/logic/LogicManager.java
  src/main/java/seedu/address/reimbursement/model/Model.java
  src/main/java/seedu/address/reimbursement/model/ModelManager.java
  src/main/java/seedu/address/reimbursement/model/Reimbursement.java
  src/main/java/seedu/address/reimbursement/model/ReimbursementList.java
  src/main/java/seedu/address/reimbursement/model/util/Description.java
  src/main/java/seedu/address/reimbursement/storage/Storage.java
  src/main/java/seedu/address/reimbursement/storage/StorageManager.java
  src/main/java/seedu/address/transaction/logic/LogicManager.java
  src/test/java/seedu/address/person/logic/LogicManagerTest.java
  src/test/java/seedu/address/person/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/person/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/reimbursement/model/ReimbursementTest.java
Labels: Integration, Reimbursement

#159 Update DG for Reimbursement Tab
  docs/DeveloperGuide.adoc
  docs/images/ReimbursementTabClassDiagram.png
  docs/images/ReimbursementTabDeadlineCommandSequenceDiagram.png
  src/main/java/seedu/address/reimbursement/logic/parser/BackCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/ExitCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/SimpleParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/SortCommandParser.java
Labels: documentation

#169 take only negative transactions
  src/main/java/seedu/address/reimbursement/model/ReimbursementList.java
Labels: Integration

#173 All tests for Reimbursement > 90%
  src/main/java/seedu/address/reimbursement/logic/commands/BackCommand.java
  src/main/java/seedu/address/reimbursement/logic/commands/ExitCommand.java
  src/main/java/seedu/address/reimbursement/logic/commands/SortAmountCommand.java
  src/main/java/seedu/address/reimbursement/logic/commands/SortDeadlineCommand.java
  src/main/java/seedu/address/reimbursement/logic/commands/SortNameCommand.java
  src/main/java/seedu/address/reimbursement/logic/parser/BackCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/CommandParserWithPersonModel.java
  src/main/java/seedu/address/reimbursement/logic/parser/DeadlineCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/DoneCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/ExitCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/IndependentCommandParser.java
  src/main/java/seedu/address/reimbursement/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/reimbursement/model/Reimbursement.java
  src/main/java/seedu/address/reimbursement/model/ReimbursementList.java
  src/main/java/seedu/address/reimbursement/model/comparators/SortByAmount.java
  src/main/java/seedu/address/reimbursement/model/exception/InvalidDeadlineException.java
  src/main/java/seedu/address/reimbursement/model/exception/NoSuchPersonReimbursementException.java
  src/main/java/seedu/address/reimbursement/model/util/Deadline.java
  src/test/java/seedu/address/reimbursement/logic/LogicManagerTest.java
  src/test/java/seedu/address/reimbursement/logic/commands/CommandTest.java
  src/test/java/seedu/address/reimbursement/logic/parser/ReimbursementTabParserTest.java
  src/test/java/seedu/address/reimbursement/model/ModelManagerTest.java
  src/test/java/seedu/address/reimbursement/model/ReimbursementListTest.java
  src/test/java/seedu/address/reimbursement/model/ReimbursementTest.java
  src/test/java/seedu/address/reimbursement/model/util/DescriptionTest.java
  src/test/java/seedu/address/reimbursement/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/ReimbursementBuilder.java
  src/test/java/seedu/address/testutil/TypicalDeadlines.java
  src/test/java/seedu/address/testutil/TypicalReimbursements.java
  src/test/java/seedu/address/testutil/TypicalTransactions.java
Labels: Reimbursement, Testing

#176 Finishes Transaction Testing (94%)
  .travis.yml
  docs/DeveloperGuide.adoc
  docs/images/HomeAddCommandMMSM.png
  docs/images/HomeAddCommandSD.png
  docs/images/HomeCommandUpdateMMSM.png
  docs/images/HomeDeleteCommandSD.png
  docs/images/HomeDeleteNameCommand.png
  docs/images/HomeUpdateReimbursement.png
  docs/images/LogicForAB.png
  docs/images/LogicForR&T.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/person/logic/LogicManager.java
  src/main/java/seedu/address/person/logic/commands/AddCommand.java
  src/main/java/seedu/address/person/logic/commands/ClearCommand.java
  src/main/java/seedu/address/person/logic/commands/Command.java
  src/main/java/seedu/address/person/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/person/logic/commands/EditCommand.java
  src/main/java/seedu/address/person/logic/commands/ExitCommand.java
  src/main/java/seedu/address/person/logic/commands/FindCommand.java
  src/main/java/seedu/address/person/logic/commands/HelpCommand.java
  src/main/java/seedu/address/person/logic/commands/ListCommand.java
  src/test/java/seedu/address/person/logic/LogicManagerTest.java
  src/test/java/seedu/address/person/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/person/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/person/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/person/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/person/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/person/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/person/model/person/PersonTest.java
  src/test/java/seedu/address/person/ui/UiPartTest.java
Labels: Testing, Transaction

#178 Update Reimbursement tab in DG
  docs/DeveloperGuide.adoc
  docs/images/LogicForR&T.png
Labels: documentation

#191 Update Reimbursement in DG
  docs/DeveloperGuide.adoc
  docs/images/DeleteCommandCashierActivityDiag.png
  docs/images/Reimbursement/ReimbursementBackCommandSD.png
  docs/images/Reimbursement/ReimbursementDeadlineCommandSD.png
  docs/images/Reimbursement/ReimbursementDoneCommandSD.png
  docs/images/Reimbursement/ReimbursementFindCommandSD.png
  docs/images/Reimbursement/ReimbursementSortCommandSD.png
  docs/images/Reimbursement/ReimbursementTabActivityDiagramDeadlineCommand.png
  docs/images/Reimbursement/ReimbursementTabActivityDiagramDoneCommand.png
  docs/images/Reimbursement/ReimbursementTabActivityDiagramFindCommand.png
  docs/images/Reimbursement/ReimbursementTabClassDiagram.png
  docs/images/Reimbursement/ReimbursementTabDeadlineCommandSequenceDiagram.png
  docs/images/Reimbursement/ReimbursementUpdateTransactionsSD.png
Labels: Reimbursement, documentation

#192 update reimbursement in UG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Reimbursement/ReimbursementBackCommand.PNG
  docs/images/Reimbursement/ReimbursementBackCommandSuccess.PNG
  docs/images/Reimbursement/ReimbursementDeadlineCommand.PNG
  docs/images/Reimbursement/ReimbursementDeadlineCommandSuccess.PNG
  docs/images/Reimbursement/ReimbursementDoneCommand.PNG
  docs/images/Reimbursement/ReimbursementDoneCommandSuccess.PNG
  docs/images/Reimbursement/ReimbursementFindCommand.PNG
  docs/images/Reimbursement/ReimbursementFindCommandSuccess.PNG
  docs/images/Reimbursement/ReimbursementSortAmountCommand.PNG
  docs/images/Reimbursement/ReimbursementSortAmountCommandSuccess.PNG
  docs/images/Reimbursement/ReimbursementSortDateCommand.PNG
  docs/images/Reimbursement/ReimbursementSortDateCommandSuccess.PNG
  docs/images/Reimbursement/ReimbursementSortNameCommand.PNG
  docs/images/Reimbursement/ReimbursementSortNameCommandSuccess.PNG
Labels: Reimbursement, documentation

#196 add reset functions to typical transactions and typical reimbursement
  docs/UserGuide.adoc
  src/test/java/seedu/address/person/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/person/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/reimbursement/logic/LogicManagerTest.java
  src/test/java/seedu/address/reimbursement/logic/commands/CommandTest.java
  src/test/java/seedu/address/reimbursement/logic/parser/ReimbursementTabParserTest.java
  src/test/java/seedu/address/reimbursement/model/ModelManagerTest.java
  src/test/java/seedu/address/reimbursement/model/ReimbursementListTest.java
  src/test/java/seedu/address/reimbursement/model/ReimbursementTest.java
  src/test/java/seedu/address/reimbursement/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalReimbursements.java
  src/test/java/seedu/address/testutil/TypicalTransactions.java
Labels: Testing
